### ISSUE TITLE
subticket macro causing slowdown?

### ISSUE THREAD

**Issue by rogeroberholtzer** [itota/trac-subtickets-plugin#15]
Hello

I am running trac 0.12.1, along with the current version of subtickets. At about the time I added subtickets, I noticed a marked slow-down in the trac site in general. I see the following in the trac log repeated for what is probably every request. I suspect this is perhaps related to
the slowdown.

2011-02-11 11:25:29,106 Trac[main] ERROR: Internal Server Error:
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/trac/web/main.py", line 511, in _dispatch_request
    dispatcher.dispatch(req)
  File "build/bdist.linux-i686/egg/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "build/bdist.linux-i686/egg/trac/web/chrome.py", line 463, in process_request
    in provider.get_htdocs_dirs() or []
  File "build/bdist.linux-i686/egg/tracsubtickets/web_ui.py", line 51, in get_htdocs_dirs
    return [('subtickets', resource_filename(__name__, 'htdocs'))]
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 841, in resource_filename
    self, resource_name
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1311, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1322, in _extract_resource
    zip_stat = self.zipinfo[zip_path]
KeyError: tracsubtickets/htdocs

If I disable the subticket macro, the speed of trac seems to be what is was previously. So subticket seems to be involved in the slowdown.

I do not know what this indicates. Perhaps these errors result in the slowdown?

**Comment by itamaro** [comment]
See issue #6
