### ISSUE TITLE
post_process_request sent a None argument

### ISSUE THREAD

**Issue by savages** [itota/trac-subtickets-plugin#19]
Ubuntu 11.04  trac 0.11

I am sorry but I am new and this is what I know now, what other things are needed to answer this problem.

2011-09-18 22:32:29,159 Trac[main] ERROR: Exception caught while post-processing request: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/trac/web/main.py", line 239, in dispatch
    self._post_process_request(req)
  File "/usr/lib/python2.7/dist-packages/trac/web/main.py", line 311, in _post_process_request
    f.post_process_request(req, _(None,)_extra_arg_count)
  File "/usr/local/lib/python2.7/dist-packages/TracSubTicketsPlugin-0.1.0-py2.7.egg/tracsubtickets/web_ui.py", line 64, in post_process_request
    ticket = data['ticket']
TypeError: 'NoneType' object is not subscriptable
2011-09-18 22:32:29,159 Trac[main] WARNING: HTTPInternalError: 500 Trac Error (Invalid action "view")

**Comment by nargov** [comment]
Having a similar problem - everything was working fine, until I installed http://trac-hacks.org/wiki/TimingAndEstimationPlugin. After creating a ticket, can't go into it anymore (says TIME_ADMIN is required, although my user has TRAC_ADMIN), and the same error is in the log.

**Comment by dbussert** [comment]
Same problem here

Traceback (most recent call last):
  File "/opt/bitnami/apps/trac/lib/Trac-1.0-py2.7.egg/trac/web/main.py", line 243, in dispatch
    self._post_process_request(req)
  File "/opt/bitnami/apps/trac/lib/Trac-1.0-py2.7.egg/trac/web/main.py", line 340, in _post_process_request
    f.post_process_request(req, _(None,)_extra_arg_count)
  File "build/bdist.linux-x86_64/egg/tracsubtickets/web_ui.py", line 65, in post_process_request
    ticket = data['ticket']
TypeError: 'NoneType' object has no attribute '__getitem__'
