### ISSUE TITLE
Error on environment upgrade

### ISSUE THREAD

**Issue by anya** [itota/trac-subtickets-plugin#7]
I followed all the steps of installation but last. Trac-admin upgrade results in an error:
Traceback (most recent call last):
  File "/usr/bin/trac-admin", line 8, in <module>
    load_entry_point('Trac==0.11.4', 'console_scripts', 'trac-admin')()
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/admin/console.py", line 1317, in run
    return admin.onecmd(command)
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/admin/console.py", line 133, in onecmd
    rv = cmd.Cmd.onecmd(self, line) or 0
  File "/usr/lib/python2.5/cmd.py", line 219, in onecmd
    return func(arg)
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/admin/console.py", line 1154, in do_upgrade
    self.__env.upgrade(backup=do_backup)
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/env.py", line 458, in upgrade
    participant.upgrade_environment(db)
  File "build/bdist.linux-i686/egg/tracsubtickets/api.py", line 87, in upgrade_environment
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/db/util.py", line 50, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/db/sqlite_backend.py", line 58, in execute
    args or [])
  File "/usr/lib/python2.5/site-packages/Trac-0.11.4-py2.5.egg/trac/db/sqlite_backend.py", line 50, in _rollback_on_error
    return function(self, _args, *_kwargs)
<b>sqlite3.OperationalError: near "?": syntax error</b>

**Comment by anya** [comment]
Moreover, something broke in my Trac installation: I keep getting internal sever errors when trying to save anything.

**Comment by fhillip** [comment]
im having a similar issue using a Virtual machine on VMServer, i have instaled in a Worstation version and its working normally.

Part of the error:

"File "/usr/lib/python2.6/dist-packages/trac/db/sqlite_backend.py", line 51, in _rollback_on_error
    return function(self, _args, *_kwargs)
sqlite3.OperationalError: near "?": syntax error"3

**Comment by MWM-Mannheim** [comment]
I have the same error here:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\admin\con
sole.py", line 107, in onecmd
    rv = cmd.Cmd.onecmd(self, line) or 0
  File "C:\Python26\lib\cmd.py", line 218, in onecmd
    return self.default(line)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\admin\con
sole.py", line 266, in default
    return cmd_mgr.execute_command(_args)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\admin\api
.py", line 123, in execute_command
    return f(_fargs)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\env.py",
line 782, in _do_upgrade
    self.env.upgrade(backup=no_backup is None)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\env.py",
line 525, in upgrade
    with_transaction(self)(participant.upgrade_environment)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\db\api.py
", line 77, in transaction_wrapper
    fn(ldb)
  File "build\bdist.win32\egg\tracsubtickets\api.py", line 104, in upgrade_envir
onment
    cursor.execute("SELECT \* FROM %s", (table.name, ))
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\db\util.p
y", line 65, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\db\sqlite
_backend.py", line 78, in execute
    result = PyFormatCursor.execute(self, _args)
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\db\sqlite
_backend.py", line 56, in execute
    args or [])
  File "C:\Python26\lib\site-packages\trac-0.12.2-py2.6-win32.egg\trac\db\sqlite
_backend.py", line 48, in _rollback_on_error
    return function(self, *args, *_kwargs)
OperationalError: near "?": syntax error

**Comment by MWM-Mannheim** [comment]
I found a solution. I deleted the "subticktes" table in the database. Then i could upgrade the database.

**Comment by rjollos** [comment]
This may have been fixed in: 900cbf532d0b57f092117286ffcc00692989b3e1. I can't say for sure that the problem has been fixed, but it was definitely created when the default database tables were changed without providing an upgrade path and bumping the db version in 253f0194d486c24febc4af68707221ab369b092f.
